package com.manohar.nova.memory;

import java.util.List;

/**
 * Service interface defining conversation memory operations.
 */
public interface MemoryService {

    /**
     * Saves a user message to the conversation history.
     *
     * @param message the message content sent by the user
     */
    void saveUserMessage(String message);

    /**
     * Saves an assistant message to the conversation history.
     *
     * @param message the message content generated by the assistant
     */
    void saveAssistantMessage(String message);

    /**
     * Retrieves the current conversation history.
     *
     * @return a list containing the conversation history
     */
    List<ConversationMessage> getConversation();

    /**
     * Clears all messages from the conversation history.
     */
    void clear();
}
